### ISSUE TITLE
Hide Cap from the Dock

### ISSUE THREAD

**Issue by mikekosulin** [CapSoftware/Cap#101]
It would be a great option to hide Cap from the dock, the tray icon is enough.

p.s. Thanks for 0.3.0, it works pretty well.

**Comment by richiemcilroy** [comment]
Great idea!

Will add an option to the settings menu

**Comment by Brendonovich** [comment]
Implemented in 5e74656c54dd9d51bf4bf9dc3a57fcdf59832bd4, will be out in the next release
