### ISSUE TITLE
Cap always accesses internal camera

### ISSUE THREAD

**Issue by mikekosulin** [CapSoftware/Cap#103]
### Description

Cap continues to use the internal camera even if another camera is selected or access is blocked. 
Expected behavior: Stop using the camera when it is switched.

### Reproduction

1. Open the cap.
2. Select "No Camera" or select another external camera.
3. Note that the application is still using the camera. (the camera LED is on and I can see via MacOS Camera Access that it still has access to the internal camera)

### Additional Context

- Cap version: `0.3.0-beta.5.2`
- Operating system, version: `macOS 14.2.1`
- Device (optional): `MacBook Air 13 m2`

<img width="764" alt="image" src="https://github.com/user-attachments/assets/63be1232-b741-4565-aea4-a811d8bdb581">

**Comment by mikekosulin** [comment]
Also, the camera should be accessed only the video circle is on the screen.

**Comment by richiemcilroy** [comment]
Hey @mikekosulin thanks for this!

Will be fixed in https://github.com/CapSoftware/Cap/pull/100, hopefully will get it live soon

**Comment by Brendonovich** [comment]
Fixed in beta 5.3
