### ISSUE TITLE
Moving from Supabase to PlanetScale/NextAuth

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/cap#11]
Pasting this from the [Cap Discord](https://discord.gg/y8gdQ3WRN3).

"This was a tough decision for me to make, but I'm moving away from Supabase (db/auth) for use in Cap.

I love Supabase, but local dev just doesn't seem viable right now for a shared codebase. Too many inconsistencies between features not being supported in local vs the deployed version (e.g. email templates). It's also pretty confusing to run migrations etc for anyone who hasn't used Supabase in the past.

Moving to a combination of PlanetScale (db), NextAuth (auth) and Drizzle (orm).

Making this decision now before V1 is live - much easier to handle now than in the future.

If you have any opposition to this - would love to hear your thoughts 🙏"

**Comment by richiemcilroy** [comment]
Branch is here:
https://github.com/cap-so/cap/tree/db-switch

**Comment by sarthaktexas** [comment]
you don't know me but i concur planetscale + drizzle >>> supabase
