### ISSUE TITLE
Debugging / error logging via Sentry

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#125]
Would like to add Sentry for error logging and debugging for both the Rust backend and Solid frontend.

Whenever an error occurs in the following functions/actions:

- Start recording
- Stop recording 
- Select camera
- Select microphone
- Copy to clipboard 
- Export video 
- Create shareable link 
- Sign in / auth redirect 

Would like to be notified correctly via sentry, logging the user's ID (from their session).

This will help us better diagnose and fix future errors.

**Comment by Harsh9485** [comment]
ok I am write staps what I do 
but you don't like particular stap you told me and correct the stap 

1 add Sentry error tracking

**Comment by Harsh9485** [comment]
if use sentry which account use for this ma account?

**Comment by richiemcilroy** [comment]
Hey @Harsh9485 you can just use your own Sentry account for now, and then I will swap out with our ID
