### ISSUE TITLE
When I click on about cap the app crashes.

### ISSUE THREAD

**Issue by gustavoabel** [CapSoftware/Cap#131]
### Description
The app is crashing when I click on the About Cap tab in the macOS menu bar.

### Reproduction

https://github.com/user-attachments/assets/7aa3a890-4642-485d-b927-6cbe2fb4d774

### Additional Context

- Cap version: 0.3.0-Beta-5.7.3
- Operating system, version: MacOS Sequoia

**Comment by migueldaipre** [comment]
I can't reproduce with Version 0.3.0-beta.8
