### ISSUE TITLE
Corrupt frame data after screen capture (macOS)

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/cap#17]
**Description**
Experiencing a bug with frame data (from screen capture) being corrupt on some Mac's. Seems to work fine on my 16" MacBook Pro, but when testing on 14" MacBook Pro's the frame image looks corrupt.

**My thoughts**
I believe this possibly stems from the stride calculation needing to be altered. This is because the frame data *can* be visible if you mess around with the stride settings - it's not always completely corrupt. The pixel data can be shown, it's just a matter of how it is represented. Also, it may be to do with the scaling factor of the device.

**Example of a corrupted frame**
<img width="1599" alt="Screenshot 2024-03-23 at 02 48 50" src="https://github.com/CapSoftware/cap/assets/33632126/71bfe58b-accb-4e04-b073-f872300b9178">

**Device Specs**
14" MacBook Pro
M1 Pro Chip
Sonoma 14.4 (also tested on early versions, e.g. 13.1)

**Resolutions tested**
1800x1169 (also 2x scale)
1512x982 (also 2x scale)
1352x878 (also 2x scale)

**Suspect code**
The code for this is located at `media.rs` which belongs to `/apps/desktop`: https://github.com/CapSoftware/cap/blob/main/apps/desktop/src-tauri/src/media.rs

The line you're looking for is `line 356`, `match capturer.frame() {`. In here, we are iterating over each row and extending the slice to send to `video_channel_sender`. This then feeds into the video ffmpeg command, at `line 437`. 

The raw frame should be packed bgra (ARGB8888). If you search for `ARGB8888` in the codebase, you'll find the `capturer` package, which ultimately creates the core graphics display stream via `CGDisplayStreamCreateWithDispatchQueue`.

**Comment by shamun-khatri** [comment]
@richiemcilroy I want to work on this but is this only related to 14" MacBook Pro and are other users also facing the same prob@richil em on any other models?

**Comment by richiemcilroy** [comment]
Hey! I can't be sure that it's definitely only 14". It seems to be on retina devices, but for some reason not my 16" 🤔 so it's pretty strange. > @richiemcilroy I want to work on this but is this only related to 14" MacBook Pro and are other users also facing the same prob@richil em on any other models?

**Comment by okhot** [comment]
@richiemcilroy is there anyway to reproduce this?

**Comment by richiemcilroy** [comment]
> @richiemcilroy is there anyway to reproduce this? 

Yeah if you have a 13" MacBook Pro you should be able to directly reproduce (or via an emulator maybe?). If you follow the contribution guide found in the readme you should be able to get started.

If you want to skip all the auth process etc, you could just manually run the desktop app in apps/desktop, and comment out the <SignIn/> component in /apps/desktop/src/page.tsx

**Comment by richiemcilroy** [comment]
hey everyone! Updated the contributing guide to show how you can get setup to develop the Cap desktop app locally. Does not require any external .env var dependencies:

https://github.com/CapSoftware/cap/blob/main/CONTRIBUTING.md

**Comment by Bhavyajain21** [comment]
> hey everyone! Updated the contributing guide to show how you can get setup to develop the Cap desktop app locally. Does not require any external .env var dependencies:
> 
> https://github.com/CapSoftware/cap/blob/main/CONTRIBUTING.md

export const resend = new Resend(process.env.RESEND_API_KEY);

It still requires the RESEND_API_KEY?

**Comment by filleduchaos** [comment]
/attempt #17

Instead of the app *only* calculating the stride by itself (which is prone to error because of padding for alignment at different native resolutions on macOS), I'm switching to letting the underlying OS framework report how many bytes per row each frame contains (and using that in tandem with the calculated stride to derive an image without padding).

**Comment by shamun-khatri** [comment]
@filleduchaos Hey How have you done that? mean I am new to open source. And wants to know how you find that solution and write code.

**Comment by richiemcilroy** [comment]
Amazing work @filleduchaos - rewarded!
