### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#182]
New dark mode toggle for Cap desktop.

Toggle should live in general settings.

When enabled, do the following:

- Change general UI theme from light to dark
- Change logo from light to dark (can supply dark version of logo)
- Toggle in Settings menu

**Comment by onyedikachi-david** [comment]
https://github.com/user-attachments/assets/7fa9eaa7-83c4-467d-b45a-90b3a9739071
