### ISSUE TITLE
Cap is using the microphone continuously

### ISSUE THREAD

**Issue by mikekosulin** [CapSoftware/Cap#189]
### Description

Cap is using the microphone continuously, even when it is not recording.

### Reproduction

- Launch the app.
- Check the macOS Control Center.

### Additional Context

- Cap version: 0.3.0-beta.10
- Operating system, version: 15.0.1 (24A348)
- Device (optional): MacBook Air M2

<img width="325" alt="image" src="https://github.com/user-attachments/assets/86943984-410a-4dd2-9671-19b78c7b8e79">

**Comment by richiemcilroy** [comment]
hey @mikekosulin - if you switch the microphone to "No Audio" it should fix this - please let me know if this is ok :) cheers!

**Comment by mikekosulin** [comment]
I believe this's a bug.

Expected behavior: mic is only activated when Cap is recording or the Cap window is active (on mic select).

What do you think?
