### ISSUE TITLE
Intel Mac Crashing

### ISSUE THREAD

**Issue by dineshroxonn** [CapSoftware/Cap#193]
### Description

Application not opening after installation

### Reproduction

Installed the version from website

### Additional Context

- Cap version:0.3-alpha25
- Operating system, version:12.7.6 Monterey
- Device (optional):macbook air 2017

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Cap [2384]
Path:                  /Applications/Cap.app/Contents/MacOS/Cap
Identifier:            so.cap.desktop
Version:               0.3.1-alpha.25 (20241128.015201)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-11-29 15:12:32.1313 +0530
OS Version:            macOS 12.7.6 (21H1320)
Report Version:        12
Anonymous UUID:        9E0C5F4B-999D-DCFB-2630-00A60F8068A5

Time Awake Since Boot: 2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: (_OBJC_CLASS_$_AVAudioApplication)
Referenced from: '/Applications/Cap.app/Contents/MacOS/Cap'
Expected in: '/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation'
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x107e3d9a2 __abort_with_payload + 10
1   dyld                          	       0x107e53ab2 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x107e53ae4 abort_with_payload + 9
3   dyld                          	       0x107e01699 dyld4::halt(char const*) + 615
4   dyld                          	       0x107dfd5b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x107dfc4e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bcb4e5f8  rdx: 0x00007ff7bcb4ea60
  rdi: 0x0000000000000006  rsi: 0x0000000000000004  rbp: 0x00007ff7bcb4e640  rsp: 0x00007ff7bcb4e5f8
   r8: 0x00007ff7bcb4e660   r9: 0x0000000000000000  r10: 0x00000000000000a8  r11: 0x0000000000000246
  r12: 0x00000000000000a8  r13: 0x00007ff7bcb4ea60  r14: 0x0000000000000004  r15: 0x0000000000000006
  rip: 0x0000000107e3d9a2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x107df7000 -        0x107e62fff dyld (*) <eea022bb-a6ab-3cd1-8ac1-54ce8cfd3333> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=33.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=33.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__CTF                               756        1 
__DATA                            55.2M      499 
__DATA_CONST                      33.3M      322 
__DATA_DIRTY                      1687K      203 
__FONT_DATA                          4K        1 
__LINKEDIT                       657.1M       17 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3200K        1 
__TEXT                           593.6M      513 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                              1.5G     1565 

-----------
Full Report
-----------

{"app_name":"Cap","timestamp":"2024-11-29 15:12:32.00 +0530","app_version":"0.3.1-alpha.25","slice_uuid":"488d0dc4-8c4f-33b6-9bd0-56aac719dccb","build_version":"20241128.015201","platform":1,"bundleID":"so.cap.desktop","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7.6 (21H1320)","incident_id":"1A6EDA3C-B72A-4487-9FE5-98481DDCE954","name":"Cap"}
{
  "uptime" : 2300,
  "procLaunch" : "2024-11-29 15:12:32.1058 +0530",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir7,2",
  "procStartAbsTime" : 2354063242667,
  "coalitionID" : 1446,
  "osVersion" : {
    "train" : "macOS 12.7.6",
    "build" : "21H1320",
    "releaseType" : "User"
  },
  "captureTime" : "2024-11-29 15:12:32.1313 +0530",
  "incident" : "1A6EDA3C-B72A-4487-9FE5-98481DDCE954",
  "bug_type" : "309",
  "pid" : 2384,
  "procExitAbsTime" : 2354088073949,
  "cpuType" : "X86-64",
  "procName" : "Cap",
  "procPath" : "\/Applications\/Cap.app\/Contents\/MacOS\/Cap",
  "bundleInfo" : {"CFBundleShortVersionString":"0.3.1-alpha.25","CFBundleVersion":"20241128.015201","CFBundleIdentifier":"so.cap.desktop"},
  "storeInfo" : {"deviceIdentifierForVendor":"2E41CD6F-BFE0-570B-AE0D-929028908479","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "so.cap.desktop",
  "crashReporterKey" : "9E0C5F4B-999D-DCFB-2630-00A60F8068A5",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: (_OBJC_CLASS_$_AVAudioApplication)","Referenced from: '\/Applications\/Cap.app\/Contents\/MacOS\/Cap'","Expected in: '\/System\/Library\/Frameworks\/AVFoundation.framework\/Versions\/A\/AVFoundation'"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":38526,"threadState":{"r13":{"value":140701999622752},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":4},"rsi":{"value":4},"r8":{"value":140701999621728},"cr2":{"value":0},"rdx":{"value":140701999622752},"r10":{"value":168},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4427340194,"matchesCrashFrame":1},"rbp":{"value":140701999621696},"rsp":{"value":140701999621624},"r12":{"value":168},"rcx":{"value":140701999621624},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289186,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379570,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379620,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4427051008,
    "size" : 442368,
    "uuid" : "eea022bb-a6ab-3cd1-8ac1-54ce8cfd3333",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703282094080,
  "size" : 19331678208,
  "uuid" : "246818c3-4b9f-3462-bcaf-fdf71975e5fe"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=33.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=33.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__CTF                               756        1 \n__DATA                            55.2M      499 \n__DATA_CONST                      33.3M      322 \n__DATA_DIRTY                      1687K      203 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       657.1M       17 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3200K        1 \n__TEXT                           593.6M      513 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                              1.5G     1565 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000032
    },
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "652886aa2c02f032beae8316"
      },
      "deploymentId" : 240000028
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir7,2, BootROM 489.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1.8 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Display: Color LCD, 1440 x 900 (Widescreen eXtended Graphics Array Plus), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB30Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Keykoard
USB Device: Wireless Receiver
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by richiemcilroy** [comment]
Hey @dineshroxonn - unfortunately we only support macOS 13+. Could you maybe try updating and trying again? Cheers
