### ISSUE TITLE
Issue with shareable link creation

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#205]
When uploading a shareable link either via the thumbnail or editor, the upload completes fine, but the response seems to hang and doesn't finish. On reload the state is as expected and the shareable link clicks through fine.

<img src="https://uploads.linear.app/af0d20a8-533e-42f9-982d-8c127173f696/6b1857f6-75e4-4768-92a4-bd476a5fe681/595b1ae0-3918-48e9-ad64-5e1784ffdc97?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FmMGQyMGE4LTUzM2UtNDJmOS05ODJkLThjMTI3MTczZjY5Ni82YjE4NTdmNi03NWU0LTQ3NjgtOTJhNC1iZDQ3NmE1ZmU2ODEvNTk1YjFhZTAtMzkxOC00OGU5LWFkNjQtNWUxNzg0ZmZkYzk3IiwiaWF0IjoxNzMzOTMwMDc5LCJleHAiOjMzMzA0NDkwMDc5fQ.dBjLQaXK_QEK3HnWvutEjeufLl7on0qFT593qx7oGJY " alt="Screenshot 2024-12-11 at 15.12.07.png" width="435" data-linear-height="320" />

**Comment by Brendonovich** [comment]
Fixed in 0.3.6
