### ISSUE TITLE
Hide recording window when recording, and create tray icon (macOS)

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#21]
On starting recording, hide the main Cap window.

Show a stop recording icon in the macOS menu bar tray.

On tray icon click, stop the recording.

**This is currently required for macOS only.**

**Requirements**
-Create menu bar tray icon. Use Cap logo as icon maybe? This can be changed later.
-When recording is active, change icon to a stop icon. Maybe use this icon from [Lucide](https://lucide.dev/icons/circle-stop).
-When recording is active, hide main Cap app recording window (keep camera overlay window as it is)

You can use [this guide](https://github.com/CapSoftware/Cap/blob/main/CONTRIBUTING.md#how-do-i-run-the-desktop-app-locally-without-needing-to-use-auth) to help you get started developing locally as quickly as possible.

**Comment by anoopw3bdev** [comment]
@richiemcilroy feel free to assign to me, have started on this

**Comment by syedbarimanjan** [comment]
can you assign this to me.
/attempt #21

**Comment by richiemcilroy** [comment]
@syedbarimanjan done!

**Comment by richiemcilroy** [comment]
Anyone have a WIP for this?

**Comment by syedbarimanjan** [comment]
> Anyone have a WIP for this?

I am working on will raise the pr.

**Comment by syedbarimanjan** [comment]
> > Anyone have a WIP for this?
> 
> I am working on it, will raise the pr.

**Comment by richiemcilroy** [comment]
Upped the bounty to $150.

**Comment by lukasgjetting** [comment]
In case it's helpful to anyone: I've set up a wip [here](https://github.com/lukasgjetting/Cap/commit/8242c04ebd182cae8319f056d26f8d5a6f30707c).

Still missing a few things:

1. Tray should only be initialized on MacOS
2. Clicking tray icon to stop recording doesn't sync the UI
3. Doesn't respect the same "min 5 sec" rule as the frontend (maybe it shouldn't?)
4. Haven't tested outside local mode, but based on the logging it seems to work correctly

**Comment by ItsEeleeya** [comment]
All requirements added [here](https://github.com/CapSoftware/Cap/compare/main...ItsEeleeya:Cap:macos-tray-icon)

There's a quit and a dedicated show button. Left clicking the tray icon shows the main window as well.
Tray icon changes when you start or stop the recording.
When recording starts all windows except camera view get hidden.
Since handling the tray click event is done in the frontend, the UI reacts correctly.

I'm hoping later I can add the camera and microphone selectors to the tray menu as well.

![Cap Tray](https://github.com/CapSoftware/Cap/assets/47112191/22b91e01-4714-48e0-9f83-84bb9b60a290)

**Comment by richiemcilroy** [comment]
> All requirements added [here](https://github.com/CapSoftware/Cap/compare/main...ItsEeleeya:Cap:macos-tray-icon)
> 
> 
> 
> There's a quit and a dedicated show button. Left clicking the tray icon shows the main window as well.
> 
> Tray icon changes when you start or stop the recording.
> 
> When recording starts all windows except camera view get hidden.
> 
> Since handling the tray click event is done in the frontend, the UI reacts correctly.
> 
> 
> 
> I'm hoping later I can add the camera and microphone selectors to the tray menu as well.
> 
> 
> 
> ![Cap Tray](https://github.com/CapSoftware/Cap/assets/47112191/22b91e01-4714-48e0-9f83-84bb9b60a290)
> 
> 

Nice @ItsEeleeya - I'll check when I get to my desktop. If you add the mic / camera selectors there I'll add another $50 to the bounty

**Comment by ItsEeleeya** [comment]
> Nice @ItsEeleeya - I'll check when I get to my desktop. If you add the mic / camera selectors there I'll add another $50 to the bounty

If there are no problems with the current features then that'll probably be for tomorrow!

**Comment by jemiluv8** [comment]
@ItsEeleeya I'd suggest you create a draft PR soon. Even with the current version of what you have

**Comment by ItsEeleeya** [comment]
> jemiluv8
It doesn't let me open another Pull Request as draft because it's already open

@richiemcilroy could you please turn the [pull request](https://github.com/CapSoftware/Cap/pull/22) to a draft?

**Comment by richiemcilroy** [comment]
Done @ItsEeleeya :)

**Comment by richiemcilroy** [comment]
Solved with https://github.com/CapSoftware/Cap/pull/22

**Comment by ItsEeleeya** [comment]
> Sorry @ItsEeleeya it's bugging I think - you may need to do /claim first with the PR linked
> 
> Reached out to Algora's support

Oh sorry do you mean comment that inside the PR or here? Like `<slash>claim #22`

**Comment by richiemcilroy** [comment]
Should be done now @ItsEeleeya :) thanks for your help! feel free to tackle another if you want to claim more

**Comment by ItsEeleeya** [comment]
Thank you, will do!
I learnt quite a bit of Rust doing this even though I've been making some private and experimental Tauri apps.
It's definitely not priority but I'd like to open some suggestions later on for the UI (the main window frame and design) and a dedicated settings window/view (I think I saw some WIP setting related stuff?).

**Comment by ItsEeleeya** [comment]
Hey @richiemcilroy 
Could you please send me a DM on Twitter? `@ItsEeleeya`
