### ISSUE TITLE
Problem with exported cropped .mp4 video

### ISSUE THREAD

**Issue by aantix** [CapSoftware/Cap#215]
### Description

The .mp4 video export is incorrect.

### Reproduction

I have an mp4 video playing in QuickTime.  My son does commentary over the video, with the webcam circle in the lower right hand corner.  

I crop the composited video down.  I export the movie.  The video output is garbled. 

Before export: 
![CleanShot 2024-12-16 at 20 25 37@2x](https://github.com/user-attachments/assets/953dd979-fefd-47d2-b6cc-94cf7b97b4be)

After export:
![CleanShot 2024-12-16 at 20 22 28@2x](https://github.com/user-attachments/assets/37bcfd65-ae1c-4a5b-a50e-8546addab260)

### Additional Context

- Cap version: 0.3.9
- Operating system, version: Mac Sonoma 14.6.1
- Device (optional): Macbook Pro

**Comment by Brendonovich** [comment]
Will have this fixed in the next release

**Comment by Brendonovich** [comment]
Fixed in 0.3.10
