### ISSUE TITLE
Combine Ffmpeg commands into one single command (macOS)

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#24]
Right now, there are two separate commands for capturing audio and video. They can be found in `media.rs` located in `apps/desktop/src-tauri`. I would like to have them combined into one single ffmpeg command to reduce system load when recording.

**Requirements**

- Create one single ffmpeg command that takes input from both the audio and video sources, muxing into one .ts file
    - This will probably be done by creating separate named pipes as the input sources
- Make sure the recording process is still performant after changing

You can use [this guide](https://github.com/CapSoftware/Cap/blob/main/CONTRIBUTING.md#how-do-i-run-the-desktop-app-locally-without-needing-to-use-auth) to help you get started developing locally as quickly as possible.

**Comment by webbdays** [comment]
@richiemcilroy 
some example usage of the command?

**Comment by richiemcilroy** [comment]
@webbdays here's a link to where both of the separate commands are located;

https://github.com/CapSoftware/Cap/blob/main/apps/desktop/src-tauri/src/media.rs#L418

**Comment by webbdays** [comment]
yes, i would like to have idea of using command with both type of inputs.

**Comment by richiemcilroy** [comment]
@webbdays it's possible but requires the use of fifo named pipes so that ffmpeg can read from the two input sources from one command.

Or if there's an alternative method with a better approach that can also be used.

**Comment by webbdays** [comment]
ok.

**Comment by ologbonowiwi** [comment]
> Make sure the recording process is still performant after changing

do we have any sort of benchmark to run before and after?

**Comment by richiemcilroy** [comment]
I guess the benchmark is just making sure that the screen capture and microphone recording is being created from a single ffmpeg command instead of two currently
