### ISSUE TITLE
Make camera overlay window more stable (macOS)

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#25]
**Issue**
It's possible to break the camera window (window turns black) when the app is first launched. Seems to happen if the app has launched in the background, then you open it after the camera preview has already initialised.

![Screenshot 2024-04-11 at 14 00 51](https://github.com/CapSoftware/Cap/assets/33632126/c30cab4a-b998-466b-a9df-ff4b117d010c)

You can use [this guide](https://github.com/CapSoftware/Cap/blob/main/CONTRIBUTING.md#how-do-i-run-the-desktop-app-locally-without-needing-to-use-auth) to help you get started developing locally as quickly as possible.

**Comment by richiemcilroy** [comment]
Hey @feliciien are you working on this?

**Comment by feliciien** [comment]
yes

Le sam. 13 avr. 2024 à 12:30, Richie McIlroy ***@***.***> a
écrit :

**Comment by richiemcilroy** [comment]
/bounty $100

Upped the bounty here, would love to get this one fixed

**Comment by richiemcilroy** [comment]
Upped the bounty here, would love to get this one fixed

**Comment by Vijaykv5** [comment]
Giving it a try @richiemcilroy 
/attempt https://github.com/CapSoftware/Cap/issues/25

**Comment by richiemcilroy** [comment]
awesome, thank you @Vijaykv5! 

You can refer to this section here in the contributing guide: 

https://github.com/CapSoftware/Cap/blob/main/CONTRIBUTING.md#how-do-i-run-the-desktop-app-locally-without-needing-to-use-auth

**Comment by ItsEeleeya** [comment]
Is the previous message automated?
I cannot reproduce the issue even when I set the app to be unfocused and minimized on start. It happens at random when I change the input video quickly between 3 devices.

Also, I keep getting the update available message even though my fork is synced with the main branch.

**Comment by ItsEeleeya** [comment]
Hey @richiemcilroy! Could you please try out [this branch](https://github.com/ItsEeleeya/Cap/tree/fix-camera-overlay-macos) and check if it's solved the issue? 
If not I'd greatly appreciate it if you could provide a little more info on how to reproduce this.

Also, I came across a few other issues trying this. It seems like switching between cameras doesn't work properly and it gets stuck on the same input the app started with (Same commit, and the latest release).

All Tao windows come into focus by default unless specified. The camera overlay is set to always be on top. After forcing them to go behind everything, the video gets hidden and then starts playing again once the window is visible and this is without any changes required it seems.
Has anyone else reported this same issue?

If the provided fix works, then I'm going to cleanup and re-do some parts of `Camera.tsx` and `MediaDeviceContext.tsx` (And probably a few more…)

**Comment by Vijaykv5** [comment]
Hey @ItsEeleeya 
I'm currently working on fixing them and would raise a PR soon

**Comment by ItsEeleeya** [comment]
> Hey @ItsEeleeya I'm currently working on fixing them and would raise a PR soon

Awesome!
It'd be great if you could also fix the device changing issue

**Comment by richiemcilroy** [comment]
hey @ItsEeleeya - you want to create your branch as a PR so I can take a look?

**Comment by Vijaykv5** [comment]
Can we close this issue @richiemcilroy if its fixed!
