### ISSUE TITLE
apple silicon support?

### ISSUE THREAD

**Issue by jatindotdev** [CapSoftware/Cap#27]
is there any plan for supporting macbook apple sillicon M series chips

**Comment by richiemcilroy** [comment]
Hey! Apple Silicon is 100% supported. I use an M1 Pro Macbook myself :)

**Comment by jatindotdev** [comment]
> hey. i don't see a M1 binary in 

@richiemcilroy

**Comment by richiemcilroy** [comment]
It's a universal build, so should work fine on both

**Comment by jatindotdev** [comment]
> It's a universal build, so should work fine on both

ohh cool. if so you guys should rename it to `-universal` since its misleading 

thanks for the quick response btw
