### ISSUE TITLE
Roadmap link is broken

### ISSUE THREAD

**Issue by mikekosulin** [CapSoftware/Cap#32]
The roadmap link on the [pricing page](https://cap.so/pricing) returns 404

<img width="604" alt="image" src="https://github.com/CapSoftware/Cap/assets/6089872/03b5ebb1-04e9-4621-b891-554677caae99">

**Comment by krishpatel023** [comment]
Its because the roadmap component does not exist. If it needs to be made from scratch using drag-and-drop, I would like to contribute to it and if there is an external platform to be linked than its ok the maintainers can fix it directly.
Do let me know, thanks :)
