### ISSUE TITLE
Infinite error loop "Recording must be for minimum of 5 seconds"

### ISSUE THREAD

**Issue by laander** [CapSoftware/Cap#33]
I tried to record a video. Duration about 10-20 seconds I think. It was spinning "Finished up.." for at least a minute, so I went away to eat some lunch and when I came back, it went like this:

https://github.com/CapSoftware/Cap/assets/222419/ff1cbb03-74e9-406b-8964-cc669f8594fe

Thought you wanted to know. GL with Cap!

🥳 🦜

**Comment by richiemcilroy** [comment]
Hey @laander - sorry for the lack of update here. Over the last couple of months we have completely redeveloped the app from the ground up, leading to the launch of Cap v0.3.0. It's a different architecture (Tauri v2 + SolidJS).

The app is now different, with no limits :) should work better now.
