### ISSUE TITLE
Intel Chip mac Application Not Available

### ISSUE THREAD

**Issue by GaoJuqian** [CapSoftware/Cap#40]
I downloaded (Cap 0.2.3 aarch64.dmg), but the display is not available. Can I add an installation on brew?

<img width="1032" alt="image" src="https://github.com/CapSoftware/Cap/assets/50407511/2161fdb1-b511-4ade-b3f1-28e6896f3df3">

2019 MacBook Pro - 14.4.1 (23E224)

**Comment by GaoJuqian** [comment]
Can you consider adding brew installation?

**Comment by krehel** [comment]
This may be related to GitHub switching the `macos-latest` runner to arm64 back in April.  

I've seen other applications suddenly stop providing x64 builds and instead provide arm64, and they surprised as its resulted in broken builds.

Found this issue because I went to add this into Homebrew.

**Comment by richiemcilroy** [comment]
This should be fixed now as per the latest release - thanks for flagging!
