### ISSUE TITLE
Web app: preview in My Caps and og image not loading 

### ISSUE THREAD

**Issue by rsfrankgo** [CapSoftware/Cap#41]
<img width="598" alt="Screenshot 2024-06-07 at 17 32 04" src="https://github.com/CapSoftware/Cap/assets/172059847/570290bd-1737-4945-acaa-b16e69ba6c86">

<img width="273" alt="Screenshot 2024-06-07 at 17 38 22" src="https://github.com/CapSoftware/Cap/assets/172059847/e5143485-0a08-48b1-8857-930895f0251b">

**Comment by richiemcilroy** [comment]
Thumbnails should be correctly generating now on new recordings :)

Working on a script which will auto generate for older recordings if no previous thumbnail was found.
