### ISSUE TITLE
Cap v0.2.6 in Mac M1 Application startup failed because ffmpeg6arm.zip cannot be decompressed

### ISSUE THREAD

**Issue by szc3h9** [CapSoftware/Cap#43]
首次启动将会下载 ffmpeg6arm.zip，但不会将其解压，导致程序未启动成功
The first launch will download ffmpeg6arm.zip, but will not unzip it, resulting in the program not launching successfully.
<img width="441" alt="image" src="https://github.com/CapSoftware/Cap/assets/82141821/ed9ec591-a822-4cef-a34d-5e991fd11a47">

当我手动解压该文件，则可以正常运行
When I manually unzip the file, it works fine
<img width="432" alt="image" src="https://github.com/CapSoftware/Cap/assets/82141821/a54c06c5-682d-408d-b6ac-797aa39e5ef0">
<img width="893" alt="image" src="https://github.com/CapSoftware/Cap/assets/82141821/fd2755b0-5e42-46de-a759-0680a0c19346">

**Comment by richiemcilroy** [comment]
Thanks for this @szc3h9, how did you download the app? via Cap.so/download, or from GitHub?

**Comment by szc3h9** [comment]
<img width="562" alt="image" src="https://github.com/CapSoftware/Cap/assets/82141821/8a73632c-70bd-47d3-84e5-d3ca66695aef">
谢谢你的回复，他们似乎看起来没有什么不同。何况，我都做了尝试，在我的mac m1上皆是如此。
Thank for your reply. They don't seem to look any different. Besides, I tried them all and they all look the same on my Mac M1

**Comment by Brendonovich** [comment]
Closing this issue as Cap 0.3 bundles the ffmpeg CLI rather than downloading it
