### ISSUE TITLE
The sign in flow is unituitive

### ISSUE THREAD

**Issue by chronark** [CapSoftware/Cap#50]
Hey, just wanted to provide feedback:

1. I went to cap.so/login
2. I entered my email
3. I clicked "continue with email"

A small banner pops up saying that I should check email, that's good, however the page body just reverts to the blank form, which makes me question whether I need to enter my email again. Furthermore after a while the banner disappears and it now looks like nothing happened at all

![CleanShot 2024-07-15 at 07 53 25@2x](https://github.com/user-attachments/assets/a3d93ccb-19cd-4640-b0b0-9f25cb04d279)

___

The form should switch out to a confirmation message imo

**Comment by ManavJoshi111** [comment]
@richiemcilroy Is this approved? If yes, can I start working on this?

**Comment by richiemcilroy** [comment]
Thank you for this @chronark - appreciate it, and agree with you!

**Comment by richiemcilroy** [comment]
@ManavJoshi111 sure feel free to take a stab at it!

**Comment by richiemcilroy** [comment]
https://github.com/user-attachments/assets/9bb7886d-81c9-49e5-bc53-82338809e0e9


Hey @chronark - implemented this new flow. Thank you for your feedback!
