### ISSUE TITLE
Build new settings window in desktop app

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#52]
Build a Settings window in the desktop app. Take inspiration from Spacedrive layout as seen in screenshot below (inspiration, not exact design). Also maybe use shadcn (we already use some of these components in `packages/ui`.  Their forms example [here](https://ui.shadcn.com/examples/forms) looks interesting.

<img width="1215" alt="Screenshot 2024-07-17 at 14 35 37" src="https://github.com/user-attachments/assets/9753cbb1-1601-417d-a962-6f7ea250befb">

**Requirements**
- [ ] Settings cog icon in main app view (next to home button)
- [ ] On click, open new larger settings window
- [ ] Sidebar with clickable tabs. Just two for now. "About" and "Settings". "About" page can just contain current app version for now. You can leave "Settings" page blank.
- [ ] Should be easy to add new tabs
- [ ] Close button in corner, showing the main app again

**Comment by syedbarimanjan** [comment]
@richiemcilroy by desktop you mean the next.js app? or the tauri app?

**Comment by richiemcilroy** [comment]
hey @syedbarimanjan, the tauri desktop app :)

**Comment by Myestery** [comment]
/attempt #52

This is possible using Sha cdn

**Comment by richiemcilroy** [comment]
you working on this @Myestery?

**Comment by Myestery** [comment]
> you working on this @Myestery?

Yes
I just started

**Comment by swaparup36** [comment]
Is this issue solved?

**Comment by Brendonovich** [comment]
Closing this issue as Cap 0.3 includes its own settings page
