### ISSUE TITLE
Account required to use 

### ISSUE THREAD

**Issue by khromov** [CapSoftware/Cap#93]
### Description

After installing Cap and allowing permissions on MacOS, the user is prompted to sign up for an account with no other way to proceed and no way to record videos. This should not be a requirement for local usage of the application.

### Reproduction

Install and run Cap

### Additional Context

- Cap version: 0.3.0
- Operating system, version: MacOS
- Device (optional):

**Comment by mayurjobanputra** [comment]
Agreed. I have no plans to use cloud for hosting (will use Gdrive)

**Comment by richiemcilroy** [comment]
Hey @khromov! For transparency, the current live version of the app available via [Cap.so/download](https://cap.so/download), will stay sign in required. However, once we release our docs/guide for self hosting, auth won't be required. Hope this helps :)
