### ISSUE TITLE
Can't Record - even though start recording is disabled

### ISSUE THREAD

**Issue by mayurjobanputra** [CapSoftware/Cap#95]
### Description

I click "Start Recording" in the app window, but it doesn't actually work. See screenshot:

Oddly, in the menu bar, I can also click start recording, and that does work and I have been able to record files, but the app window button doesn't.  

![image](https://github.com/user-attachments/assets/942a720e-9aca-46b8-9869-af09bf1d3a93)

### Reproduction

Start the app from Finder, click "Start Recording" in app window. 
 
### Additional Context

Mac M2 / 0.3.0 - beta 5.2
I have no debug logs btw - no such file as indicated

-->

**Comment by richiemcilroy** [comment]
Hey @mayurjobanputra - think this might currently be a problem with some Logitech webcams, the same happens to me with mine.

If you restart the app and record without your webcam, does it work fine? 

We're on the case and will have a fix up soon!

**Comment by Brendonovich** [comment]
Fixed in 9f12454c9b9a, framerate issue still exists and is being tracked in #97

**Comment by mayurjobanputra** [comment]
> Hey @mayurjobanputra - think this might currently be a problem with some Logitech webcams, the same happens to me with mine.
> 
> If you restart the app and record without your webcam, does it work fine?
> 
> We're on the case and will have a fix up soon!

If I record without camera, from the menu bar, then yes, it does work. But then the app window appears but then disappears right away (so can't select mic or window either)

Looking forward to the fix :)

**Comment by mayurjobanputra** [comment]
Its unclear to me if the latest is on published on cap.so. If it isn't yet, then ignore below. Otherwise, you may need to re-open this bug @Brendonovich 

Thx

https://github.com/user-attachments/assets/fab8874e-69f6-4b54-b420-83783431003e

**Comment by mayurjobanputra** [comment]
Some of the cap files that are 48 bytes attached in a zip

[cap-files.zip](https://github.com/user-attachments/files/17274647/cap-files.zip)

**Comment by Brendonovich** [comment]
The fix will be available in beta 5.3, being released soon
