### ISSUE TITLE
Video framerate is potato

### ISSUE THREAD

**Issue by mayurjobanputra** [CapSoftware/Cap#97]
### Description

It may be related to the other bug I posted [here](https://github.com/CapSoftware/Cap/issues/95), but when looking at the video, the framerate looks like 5 fps. 

### Additional Context

- Cap version:
- Operating system, version:
- Device (optional):

Mac M2 / 0.3.0 - beta 5.2
I have no debug logs btw - no such file as indicated

**Comment by mayurjobanputra** [comment]
OK, so it is related to the previous bug mentioned. The framerate goes to potato mode after I click "start recording" as described in https://github.com/CapSoftware/Cap/issues/95

**Comment by Brendonovich** [comment]
Fixed in beta-5.4
